apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: javasample
  namespace: idi2021
spec:
  resources:
    kubernetesResource:
      serviceType: NodePort
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers: null
  serviceAccountName: tekton
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: javasample-build-and-deploy
    template:
      ref: javasample-build-and-deploy