---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push-gke-deploy
  namespace: idi2021
  labels:
    app.kubernetes.io/version: '0.1'
  annotations:
    tekton.dev/pipelines.minVersion: '0.12.1'
    tekton.dev/tags: build, push, deploy
spec:
  resources:
      - name: source-repo
        type: git
      - name: builtImage
        type: image
  params:
    - name: clusterName
      type: string
      description: Name of target GKE cluster to deploy to.
    - name: clusterLocation
      type: string
      description: Zone/region of target GKE cluster to deploy to.
    - name: clusterProject
      type: string
      description: Project of target GKE cluster to deploy to.
  tasks:
    - name: build-push
      taskRef:
        name: build-push
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
           - name: builtImage
             resource: builtImage
    - name: gke-deploy
      taskRef:
        name: gke-deploy
      runAfter:
        - build-push
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: builtImage
      params:
      - name: clusterName
        value: $(params.clusterName)
      - name: clusterLocation
        value: $(params.clusterLocation)
      - name: clusterProject
        value: $(params.clusterProject)