apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: javasample-git
  namespace: idi2021
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/ggalloro/javasample-tkn.git
