apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: kcn-mi
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: premium-rwo 
  accessModes:
    - ReadWriteOnce