apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: kcditaly
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: standard-rwo 
  accessModes:
    - ReadWriteOnce