apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: hello-parameters-taskrun
  namespace: kcn-mi
spec:
  taskRef:
    name: hello-parameters
  params:
    - name: recipient
      value: 'KCN Milano !'
