apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: echo-hello-parameters-task-run
  namespace: kcditaly
spec:
  taskRef:
    name: echo-hello-parameter
  params:
    - name: recipient
      value: 'kcditaly'
