apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
  namespace: devopsdays
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Goodbye World !"
