apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-parameters
  namespace: devopsdays
spec:
  params:
    - name: recipient
      description: Recipient of Hello 
      default: World
      type: string
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello $(params.recipient)"
