apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: javasample-build-and-deploy
  namespace: idi2021
spec:
  params:
  - description: The repository url to build and deploy.
    name: URL
  - description: The revision to build and deploy.
    name: REVISION
  - description: Name of target GKE cluster to deploy to.
    name: clusterName
  - description: Zone/region of target GKE cluster to deploy to.
    name: clusterLocation
  - description: Project of target GKE cluster to deploy to.
    name: clusterProject
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: javasample-build-and-deploy-
      namespace: idi2021
    spec:
      params:
      - name: clusterName
        value: $(params.clusterName)
      - name: clusterLocation
        value: $(params.clusterLocation)
      - name: clusterProject
        value: $(params.clusterProject)
      pipelineRef:
        name: build-push-gke-deploy
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(tt.params.REVISION)
          - name: url
            value: $(tt.params.URL)
          type: git
      - name: builtImage
        resourceSpec:
          params:
          - name: url
            value: europe-west1-docker.pkg.dev/galloro-demos/tektoncd/javasample
          type: image
      serviceAccountName: tekton
