apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: javasample-build-and-deploy
  namespace: idi2021
spec:
  params:
  - name: URL
    value: https://github.com/$(body.repository.full_name)
  - name: REVISION
    value: $(body.head_commit.id)
  - name: NAMESPACE
    value: idi2021
  - name: clusterName
    value: gke-cluster
  - name: clusterLocation
    value: europe-west1-b
  - name: clusterProject
    value: galloro-demos
