apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: javasample-build-and-deploy
  namespace: kcn-mi
spec:
  params:
  - description: The repository url to build and deploy.
    name: URL
  - description: The revision to build and deploy.
    name: REVISION
  - description: Name of target GKE cluster to deploy to.
    name: clusterName
  - description: Zone/region of target GKE cluster to deploy to.
    name: clusterLocation
  - description: Project of target GKE cluster to deploy to.
    name: clusterProject
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: javasample-build-and-deploy-
      namespace: kcn-mi
    spec:
      workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: source-pvc
      params:
      - name: clusterName
        value: $(tt.params.clusterName)
      - name: clusterLocation
        value: $(tt.params.clusterLocation)
      - name: clusterProject
        value: $(tt.params.clusterProject)
      pipelineRef:
        name: pipeline-e2e
      serviceAccountName: tekton
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: javasample-build-and-deploy
  namespace: kcn-mi
spec:
  params:
  - name: URL
    value: $(body.repository.url)
  - name: REVISION
    value: $(body.head_commit.id)
  - name: NAMESPACE
    value: kcn-mi
  - name: clusterName
    value: gke-cluster
  - name: clusterLocation
    value: europe-west1-b
  - name: clusterProject
    value: galloro-demos
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: javasample
  namespace: kcn-mi
spec:
  resources:
    kubernetesResource:
      serviceType: NodePort
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers: null
  serviceAccountName: tekton
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: javasample-build-and-deploy
    template:
      ref: javasample-build-and-deploy
