# DEPRECATED: TO BE REMOVED
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: old-build-push
  namespace: kcn-mi
spec:
  params:
  - name: pathToContext
    description:
      The build directory used by img
    default: $(resources.inputs.source-repo.path)
  - name: pathToDockerFile
    type: string
    description: The path to the dockerfile to build
    default: $(resources.inputs.source-repo.path)/Dockerfile
  resources:
    inputs:
      - name: source-repo
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: maven-package
      image: gcr.io/cloud-builders/mvn
      workingDir: $(params.pathToContext)
      args: ['package','-Dmaven.test.skip=true']
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.builtImage.url)
        - --context=$(params.pathToContext)