apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
spec:
  containers:
  - name: kaniko-warmer
    image: gcr.io/kaniko-project/warmer:latest
    args: ["--cache-dir=/cache",
           "--image=maven:alpine",
           "--image=openjdk:8-jdk-alpine"]
    volumeMounts:
      - name: kaniko-cache
        mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
              claimName: cache-pvc
