apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn-build
  namespace: devopsdays
spec:
  workspaces:
    - name: source
  steps:
    - name: maven-package
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)
      args: ['package','-Dmaven.test.skip=true']